FROM centos:7

COPY conf/nginx.repo /etc/yum.repos.d/nginx.repo

RUN \
    yum install -y nginx && \
    yum install -y yum-utils && \
    yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm

COPY conf/epel.repo /etc/yum.repos.d/epel.repo

RUN \
    yum repolist && \
    yum -y install \
        # php \
        php-common \
        php-fpm \
        php-cli && yum clean all
        # php-gd \
        # php-curl \
        # php-mysqlnd && yum clean all

RUN mkdir /nginx_php

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY conf/test.php /nginx_php

COPY conf/start.sh /start.sh

RUN chmod +x /start.sh

CMD /start.sh


