FROM maven:3.8.7-openjdk-18-slim as builder

COPY app-maven /app

WORKDIR /app
RUN mvn package 

FROM openjdk:18-jdk-alpine

COPY --from=builder /app/target/my-app-1.0-SNAPSHOT.jar /app.jar

CMD java -jar /app.jar